version: "3.7"
services:
  customer-ms:
    build:
      context: ./customer
    container_name: customer-ms
    ports:
      - "8080:8080"
  mongodb_db:
    image: mongo:latest
    container_name: customer-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: customer_db
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
volumes:
 mongodb_data: